# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27002b79590499f5428594426dd8bc75417e004bd0181fe80b6d7860ca42c42df9341876cdcd7247b147b5d39a1917497722839e2a48cb24835f473ed2952f79

test:
  secret_key_base: 139b5543e6a707a7070a12fa24ca3d702fabecb613e3e107a760a4ab94b62c22bb15663551591765165e03a2a392afa8097520f4f0a9bf57acb3f425dbb4fda8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
